### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by spougkakiotis** [JuliaSmoothOptimizers/HSL.jl#26]
Hello, 

I am trying to install ma97 and interface it with Julia in a Windows machine. I tried your code, but I get this error:

      error("Your platform (\"$(Sys.MACHINE)\", parsed as \"$(triplet(platform_key_abi()))\") is not supported by this package because of dependency $vname")

From the comments, I can't quite understand what that error exactly means.

Also, I have just recieved the latest version of Ma97 and it is 2.5.0, while the file is written for 2.4.0. Hence, I changed the string to be compatible with the file I have. Could it be that this is the reason for the problem? Or is this code created only for specific machines? It is not clear in the readme file, which extra packages I should install in order for the build.jl function to work. 

I would really appreciate it if you could help me.

Many thanks

**Comment by abelsiqueira** [comment]
Hello @spougkakiotis, this is a two-part problem:

1- We made changes to use `BinaryProvider`, but we're depending on an update to [OpenBLASBuilder](https://github.com/JuliaLinearAlgebra/OpenBLASBuilder/issues/11). Currently, I'm building it locally, so we're using a limited set of platforms based on what we use (Linux and OSX) because it takes over an hour for each platform and my computer is barely usable during it.
2- We haven't updated to use Ma97 2.5.0 yet.

If you're willing to help, I can try building `OpenBLASBuilder` locally for Windows as well, and you can try to update HSL.jl to Ma97 2.5.0 and make a pull request. Let me know if you're interested.
Are you on 32 or 64 bits?

**Comment by spougkakiotis** [comment]
Thank you for your quick and detailed answer. Answering to your question, i am using a 64 bit machine.
Howerver, I am new to Julia, and there are various parts of the code that I am not able to to fully understand. Hence, I don't think I will be able to help.

**Comment by abelsiqueira** [comment]
That's a pity, but I hope more people on Windows will appear to help. I'll leave this open so we can try releasing Windows binaries at some points and updating to MA97 2.5.0.

**Comment by dpo** [comment]
@spougkakiotis It should be straightforward to submit a pull request to upgrade to MA97 2.5.0. I doubt much has changed in the interface and I can test locally. All that should change are lines 7 and 8 here: 
https://github.com/JuliaSmoothOptimizers/HSL.jl/blob/master/deps/build.jl#L8.

Besides that, we'll need to build Windows binaries for OpenBLAS.

**Comment by abelsiqueira** [comment]
I have created the Windows binaries overnight and updated `build/dep_openblas.jl` in the branch [`windows_build`](https://github.com/abelsiqueira/HSL.jl/tree/windows-build). You should use that.

1- Shouldn't be necessary.
2- Find a sha256 hash tool and apply to the .tar.gz.
3- Don't know, maybe it's `dll`, but better test the way it is first.

**Comment by dpo** [comment]
Thanks @abelsiqueira !

@spougkakiotis I don't know Windows well, but I believe you're going to have to use MinGW/MSYS to get MA97 to compile (certainly, our build.jl script will not work with "native" compilers). MinGW/MSYS give you a linux-like environment but produce native libraries.

Here's a way to compute the sha256 on Windows (untested): https://bhoover.com/how-to-verify-checksum-windows/

**Comment by spougkakiotis** [comment]
Thank you for the helpful answers. 

I found the new Hash-key, it is: 9ceb858f09045d406c3cf399dcc07b4c7f716f29a5e5f55a77dc8b09d55e0c4e

I cloned the windows_build in C:\\Users\\username\\.julia\\dev\\HSL

In build.jl, I changed Lines 7 & 8 (new version string and new hask key). I checked that the hash function is correct, by comparing the hash key generated for Ma57 5.2..0 which I have available, to that listed in the ma57 branch. 

I get the following error message: 

ERROR: LoadError: LoadError: IOError: could not spawn `./configure '--prefix=C:\Users\sppou\.julia\dev\HSL\deps\usr' F77=gfortran CFLAGS=-fPIC 'FFLAGS=-fPIC -fopenmp' 'FCFLAGS=-fPIC -fopenmp' '--with-blas=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lopenblas' '--with-metis=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lcoinmetis'`: no such file or directory
(ENOENT)

**Comment by dpo** [comment]
Could you please outline all the steps that led to the error message? Are you in MinGW/MSYS?

**Comment by spougkakiotis** [comment]
No, I am running the installation through ATOM. 

Below is the full message:
Error: Error building `HSL`:
│ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges
│ └ @ Base.Filesystem file.jl:789
│ [ Info: building ma97
│ ERROR: LoadError: LoadError: IOError: could not spawn `./configure '--prefix=C:\Users\sppou\.julia\dev\HSL\deps\usr' F77=gfortran CFLAGS=-fPIC 'FFLAGS=-fPIC -fopenmp' 'FCFLAGS=-fPIC -fopenmp' '--with-blas=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lopenblas' '--with-metis=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lcoinmetis'`: no such file or directory
(ENOENT)
│ Stacktrace:
│  [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:367
│  [2] (::getfield(Base, Symbol("##493#494")){Cmd})(::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:509
│  [3] setup_stdio(::getfield(Base, Symbol("##493#494")){Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:490
│  [4] #_spawn#492(::Nothing, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:508
│  [5] _spawn at .\process.jl:504 [inlined]
│  [6] #run#503(::Bool, ::Function, ::Cmd) at .\process.jl:662
│  [7] run(::Cmd) at .\process.jl:661
│  [8] top-level scope at none:0
│  [9] include at .\boot.jl:317 [inlined]
│  [10] include_relative(::Module, ::String) at .\loading.jl:1044
│  [11] include(::Module, ::String) at .\sysimg.jl:29
│  [12] include(::String) at .\client.jl:392
│  [13] top-level scope at C:\Users\sppou\.julia\dev\HSL\deps\build.jl:70
│  [14] include at .\boot.jl:317 [inlined]
│  [15] include_relative(::Module, ::String) at .\loading.jl:1044
│  [16] include(::Module, ::String) at .\sysimg.jl:29
│  [17] include(::String) at .\client.jl:392
│  [18] top-level scope at none:0
│ in expression starting at C:\Users\sppou\.julia\dev\HSL\deps\build_hsl_ma97.jl:10
│ in expression starting at C:\Users\sppou\.julia\dev\HSL\deps\build.jl:17
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

**Comment by dpo** [comment]
I don't know if we can make this work with Cygwin, and I don't know whether Atom would know anything about Cygwin. Could you try to build from a Julia command prompt in the Cygwin "terminal"?

**Comment by spougkakiotis** [comment]
I will try to set-up julia in Cygwin and see what happens.

**Comment by dpo** [comment]
Sorry about that. Could you paste the compiler error here?

**Comment by spougkakiotis** [comment]
I did not keep the file. But I remember that it said something like:
found mingw64-x86_64-gcc-fortran but a file with name ..crypto..(something) is missing. It gave an error and terminated. 

Then, it said as a fix, that I should clean OPENBLAS and re-run make with THREAD_NUM=0. However, when I did that the make OPENBLAS_THREAD_NUM=0 run for way too long and I simply stopped it. 

Anyway, I can't seem to find a fix. The error that I get in atom is probably related to the incompatibility of the paths in Linux with those in Windows (since the error I get is in Line 10 of file build_hsl_ma97.jl). 
In any case, if I can't run HSL in atom, then I won't use it, since coding in CygWin seems quite uncomfortable. 

I hope you will find someone that will help you fix the problem.

**Comment by DoctorDro** [comment]
Dear all, 
I would like to report 2 problems. Windows installation and MKL instead of OpenBLAS. Try to use MKL whenever possible, in several cases you get better performance. Anyway. Regarding the windows installation problems, ./configure cannot run from within windows, you need MinGW64 (msys2). Unfortunately, things get messy with the Windows path names "\\" vs "/". If you give the environmental variable using ENV["HSL_MA57_PATH"] = "C:\\bla\\blabla\\", and use MinGW64 to allow for ./configure to run you will get an archive PATH not found problem. If you give the ENV["HSL_MA57_PATH"] = "/c/bla/blabla/", then you still get a similar problem with other directories for metis, openblas, etc which are defined using "\\" in a windows environment. This is a design flaw of Julia from the very beginning. They should accept every path name in Unix style (using / instead of \\) and embed in Julia under windows a bash shell, as Git does or require MSYS as dependency. Then they would solve all their problems on every platform. 

So to solve this problem, one should first convert all pathnames to Unix style before running ./configure otherwise he is doomed. And of course Julia should run from within a bash shell (Git's bash shell). I was searching yesterday for a Julia function that converts Paths from Windows style to Unix style but I could not find one. Unbelievable. And I do not want to use a reg expression for that. There should be functions provided by Julia encapsulating reg expression or whatever else. Since Julia is multi-platform they should predict that they will have to switch from \\ to / and they should had provided a mechanism to do that automatically if not manually via function calls dedicated for that purpose and not reg expressions.

**Comment by DoctorDro** [comment]
> No, I am running the installation through ATOM.
> 
> Below is the full message: Error: Error building `HSL`: │ ┌ Warning: On Windows, creating file symlinks requires Administrator privileges │ └ @ Base.Filesystem file.jl:789 │ [ Info: building ma97 │ ERROR: LoadError: LoadError: IOError: could not spawn `./configure '--prefix=C:\Users\sppou\.julia\dev\HSL\deps\usr' F77=gfortran CFLAGS=-fPIC 'FFLAGS=-fPIC -fopenmp' 'FCFLAGS=-fPIC -fopenmp' '--with-blas=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lopenblas' '--with-metis=-LC:\Users\sppou\.julia\dev\HSL\deps\usr\lib -lcoinmetis'`: no such file or directory (ENOENT) │ Stacktrace: │ [1] _jl_spawn(::String, ::Array{String,1}, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:367 │ [2] (::getfield(Base, Symbol("##493#494")){Cmd})(::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:509 │ [3] setup_stdio(::getfield(Base, Symbol("##493#494")){Cmd}, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:490 │ [4] #_spawn#492(::Nothing, ::Function, ::Cmd, ::Tuple{RawFD,RawFD,RawFD}) at .\process.jl:508 │ [5] _spawn at .\process.jl:504 [inlined] │ [6] #run#503(::Bool, ::Function, ::Cmd) at .\process.jl:662 │ [7] run(::Cmd) at .\process.jl:661 │ [8] top-level scope at none:0 │ [9] include at .\boot.jl:317 [inlined] │ [10] include_relative(::Module, ::String) at .\loading.jl:1044 │ [11] include(::Module, ::String) at .\sysimg.jl:29 │ [12] include(::String) at .\client.jl:392 │ [13] top-level scope at C:\Users\sppou.julia\dev\HSL\deps\build.jl:70 │ [14] include at .\boot.jl:317 [inlined] │ [15] include_relative(::Module, ::String) at .\loading.jl:1044 │ [16] include(::Module, ::String) at .\sysimg.jl:29 │ [17] include(::String) at .\client.jl:392 │ [18] top-level scope at none:0 │ in expression starting at C:\Users\sppou.julia\dev\HSL\deps\build_hsl_ma97.jl:10 │ in expression starting at C:\Users\sppou.julia\dev\HSL\deps\build.jl:17 └ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\Pkg\src\Operations.jl:1097

You need to install msys2 and then start julia from the MinGW64 terminal. Things are easier, but somebody has to revise the whole code using specializations via checking system as described here:
[https://docs.julialang.org/en/v1/manual/handling-operating-system-variation/](url). For the time being a Julia function should be introduced to switch path names from Windows to Unix style. If it does not exists in BaseFilePaths.jl or FilePaths.jl or elsewhere, then for the time being it should be implemented, and also C: should be replaced by /c.

**Comment by amontoison** [comment]
@DoctorDro @spougkakiotis 
For information, we released [JuliaHSL](https://licences.stfc.ac.uk/product/julia-hsl).
