### ISSUE TITLE
Thread count

### ISSUE THREAD

**Issue by mtanneau** [JuliaSmoothOptimizers/HSL.jl#40]
I want to restrict Ma57 to using a single thread.
Ideally, I would only need to do 
```julia
LinearAlgebra.BLAS.set_num_threads(1)
```
but, if I understand the build steps correctly, the package builds its own OpenBlas libary.

Is there any way one can control the number of threads there?

**Comment by dpo** [comment]
This package builds its own BLAS/LAPACK if it can't detect those libraries. We can't use the Julia ones because its symbols have been mangled. So I imagine you would simply set an environment variable before firing up Julia to restrict the number of threads in whatever BLAS library you're using. Check `ldd deps/usr/lib/libhsl_ma57.so` to find out what BLAS is being used.

**Comment by dpo** [comment]
Closing because the build system has changed and we now rely on a JLL for the BLAS.
