### ISSUE TITLE
Runtime error with libopenblas

### ISSUE THREAD

**Issue by bjack205** [JuliaSmoothOptimizers/HSL.jl#70]
I'm getting a strange behavior on an x86 AMD machine (I can run everything just fine on my Intel laptop). When trying to run the tests I get:
```
ERROR: LoadError: could not load library "/home/brian/.julia/dev/HSL/deps/usr/lib/libhsl_ma97.so"
libopenblas.so: cannot open shared object file: No such file or directory
```
It's not clear to me what this message is saying, I'm guessing it's having troubles linking again libopenblas? The build step runs fine, I even get this output during the configure step:
```
checking for sgemm_ in -L/home/brian/.julia/artifacts/7fca6a59f5903d74ab82fd8c36b7656125da4318/lib -lopenblas... yes
checking for cheev_... yes
checking for METIS library... checking for metis_nodend_ in -L/home/brian/.julia/artifacts/21426dc9da406ede1def01afaf9e86678d0f84ad/lib -lmetis... yes
```
So it found the library just fine. Any ideas as to what the problem is?

**Comment by dpo** [comment]
As it happens, I am investigating the same issue on macOS as we speak. I think the issue may be that libopenblas was installed from OpenBLAS32_jll and, on my machine, Julia decided to install a version linked against libgfortran.4. However, my gfortran compiler links against libgfortran.5.

In my case too the build goes through nicely but the tests fail because of libopenblas.

**Comment by dpo** [comment]
Starting Julia with
```
DYLD_FALLBACK_LIBRARY_PATH=/full/path/to/artifact/lib julia
```
does the trick on macOS. I'm looking for a cross-platform solution.
